name: 'Add TDD Question'
description: 'Add a TDD feedback question to newly opened pull requests'
runs:
  using: 'composite'
  steps:
    - name: Add TDD Question
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const script = fs.readFileSync(path.join('${{ github.action_path }}', 'src', 'addTDDQuestion.js'), 'utf8');
          eval(script);
